# Generated by Django 6.1 on 2026-08-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_TRANSITO', 'En Tránsito'), ('LISTO', 'Listo para Entrega'), ('ENTREGADO', 'Entregado')], default='RECIBIDO', max_length=15)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categoria', models.CharField(choices=[('FAMILIARES', 'Familiares'), ('PARTY GAMES', 'Party Games'), ('ESTRATEGIA', 'Estrategia')], max_length=20)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
